@startmindmap
skinparam topurl StructureDefinition-

*[#FFBBCC] [[HeaderImagingOrder.html Imaging Order Header]]
**[#lightgreen] Imaging Order Subject
/'    Shell we keep or not?
** Preferred Health Professional
'/
**[#lightgreen] Health Insurance and Payment Information
/' ***_ Health insurance code
***_ Health insurance name
***_ Health insurance number '/
**[#lightgreen] Coverage Information
/'
** Attestation
***_ Attester
***_ DateTime
** Legal authentication
***_ Legal authenticator
***_ DateTime
'/
**[#lightgreen] Document Metadata
***_ Document ID
***_ Document Type
***_ Document Status
***_ Document date and time
***_ Document Title
***_ Order Custodian
***_ Confidentiality
***_ Language
***_ Version
**[#lightgreen] Imaging Order Author
**[#lightgreen] Additional Recipient
**[#lightgreen] Requested Performer
**[#lightgreen] Digital Signature
***_ Electronic Signature or Document Seal
***_ Electronic Timestamp
/' ** Intended recipient
** Authorship
***_ Author
***_ DateTime
** Attestation
***_ Attester
***_ DateTime
** Legal authentication
***_ Legal authenticator
***_ DateTime
** Document metadata
***_ Document ID
***_ Document type
***_ Document status
***_ Period
***_ Report date and time
***_ Document title
***_ Event type
***_ Specialty
***_ Report custodian
***_ Document format
***_ Confidentiality
***_ Language
***_ Version
***_ Study Instance UID
***_ Accession number '/
@endmindmap