Logical: ImageSupportingInformationCz
Id: ImageSupportingInformationCz
Title: "A.3.1 - Supporting Information"
Description: """Supporting Information - Information and data communicated by the imaging methods department that has an impact on the execution of the order or the interpretation of the examination results"""

* insert SetFmmandStatusRule ( 0, draft )

*  biometricData 1..1 BackboneElement "A.3.1.1 Bimetric Data" """If the required clinical data are available, it is mandatory."""
*  weight 1..1 BackboneElement "A.3.1.2 Weight" """Subject weight"""
*  weight.valueQuantity 1..1 Quantity "A.3.1.2.1 Weight value" """Data value including unit of measurement."""
*  weight.code 1..1 CodeableConcept "A.3.1.2.2 Weight code" """Observation code identifying the meaning of the weight data"""
*  weight.dateTime  0..1 dateTime "A.3.1.2.3 Weight date and time" """The date of weight discovery is stated if it is different from the date of order issuance."""
*  height 1..1 BackboneElement "A.3.1.3 Height" """Subject height"""
*  height.valueQuantity 1..1 Quantity "A.3.1.3.1 Height value" """Data value including unit of measurement."""
*  height.code 1..1 CodeableConcept "A.3.1.3.2 Height code" """Observation code identifying the meaning of the height data"""
*  height.dateTime  0..1 dateTime "A.3.1.3.3 Height date and time" """The date of height discovery is stated if it is different from the date of order issuance.""" 
*  otherRelevantClinicalInformation 0..1 BackboneElement "A.3.1.4 Other relevant clinical information" """Other relevant clinical information"""
*  otherRelevantClinicalInformation.code 0..* CodeableConcept "A.3.1.4.1 Code of other information" """Diagnoses and other clinical information that may affect the course or result of the examination or its interpretation (e.g. heart failure, claustrophobia, renal failure)""" 
*  otherRelevantClinicalInformation.text 0..1 string "A.3.1.4.2 Text of other information" """Clinical information necessary for correct order execution or interpretation of results."""
*  medication 0..* BackboneElement "A.3.1.5 Medication" """Medication block containing information about medication that has an impact on the course or result of the examination or its interpretation."""
*  medication.identifier 0..* Identifier "A.3.1.5.1 Medication identifier" """Identifier of medication"""
*  medication.code 0..* code "A.3.1.5.2 Medication code" """Code of medication"""
*  medication.amount 0..1 Ratio "A.3.1.5.3 Ratio" """Amount of drug in package"""
*  implant 0..* BackboneElement "A.3.1.6 Implant" """List of implants or devices that affect the course of the examination or its interpretation."""
*  implant.type 1..1 CodeableConcept "A.3.1.6.1 Implant type" """Type of implant"""
*  implant.identifier 0..* Identifier "A.3.1.6.2 Implant identifier" """Standardized identifier, e.g. UDI, according to EU Regulation 2017/745, ZP code according to the health insurance company catalog"""
*  implant.model 1..1 string "A.3.1.6.3 Implant model" """Specifies a specific model"""
*  implant.bodyPart 0..* CodeableConcept "A.3.1.6.4 Body part" """Body part where it is implanted"""
*  urgentInformation 0..1 BackboneElement "A.3.1.7 Urgent information" """Urgent information block in the same structure as in other types of documents (discharge report, patient summary)"""
*  urgentInformation.allergyIntolerance 1..* BackboneElement "A.3.1.7.1 Allergy intolerance" """Allergies and intolerances that may affect order fulfillment or interpretation of results"""
*  urgentInformation.warnings 0..* string "A.3.1.7.2 Warning" """Warnings and notices that may affect order fulfillment or interpretation of results"""
*  limitationOfPatientMobility 1..1 BackboneElement "A.3.1.8 Limitation of patient mobility" """Describes the patient's mobility limitations"""
*  otherInformation 0..* BackboneElement "A.3.1.9 Other information" """Other formalized observation communicated to the implementing workplace"""
*  otherInformation.dateTime 0..1 dateTime "A.3.1.9.1 Date and time of information" """Date of information discovery, stated if different from the date of order"""
*  otherInformation.code 1..1 CodeableConcept "A.3.1.9.2 Code of information" """Observation code identifying the meaning of the observation (week of gestation, etc.)"""
*  otherInformation.value 0..1 Quantity "A.3.1.9.3 Value of information" """Observation value including unit of measurement."""
